export const cards = [
  {
    word: 'Bird',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Птица',
    category: 'Animals',
    image: './nature/bird.png',
    audioSrc: './audio/bird.mp3',
    id: 0,
    categoryId: 1,
  },
  {
    word: 'Cactus',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Кактус',
    category: 'Animals',
    image: './nature/cactus.png',
    audioSrc: './audio/cactus.mp3',
    id: 1,
    categoryId: 1,
  },
  {
    word: 'Deer',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Олень',
    category: 'Animals',
    image: './nature/deer.png',
    audioSrc: './audio/deer.mp3',
    id: 2,
    categoryId: 1,
  },
  {
    word: 'Fox',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Лиса',
    category: 'Animals',
    image: './nature/fox.png',
    audioSrc: './audio/fox.mp3',
    id: 3,
    categoryId: 1,
  },
  {
    word: 'Ladybug',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Божья коровка',
    category: 'Animals',
    image: './nature/ladybug.png',
    audioSrc: './audio/ladybug.mp3',
    id: 4,
    categoryId: 1,
  },
  {
    word: 'Whale',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Кит',
    category: 'Animals',
    image: './nature/whale.png',
    audioSrc: './audio/whale.mp3',
    id: 5,
    categoryId: 1,
  },
  {
    word: 'Wood',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Дерево',
    category: 'Animals',
    image: './nature/wood.png',
    audioSrc: './audio/wood.mp3',
    id: 6,
    categoryId: 1,
  },
  {
    word: 'Jellyfish',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Медуза',
    category: 'Animals',
    image: './nature/jellyfish.png',
    audioSrc: './audio/jellyfish.mp3',
    id: 7,
    categoryId: 1,
  },
  {
    word: 'Accordion',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Аккордеон',
    category: 'Musical instruments',
    image: './music/accordion.png',
    audioSrc: './audio/accordion.mp3',
    id: 8,
    categoryId: 2,
  },
  {
    word: 'Bass guitar',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Басс гитара',
    category: 'Musical instruments',
    image: './music/bass.png',
    audioSrc: './audio/bass-guitar.mp3',
    id: 9,
    categoryId: 2,
  },
  {
    word: 'Drums',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Барабаны',
    category: 'Musical instruments',
    image: './music/drums.png',
    audioSrc: './audio/drums.mp3',
    id: 10,
    categoryId: 2,
  },
  {
    word: 'Microphone',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Микрофон',
    category: 'Musical instruments',
    image: './music/microphone.png',
    audioSrc: './audio/microphone.mp3',
    id: 11,
    categoryId: 2,
  },
  {
    word: 'Record player',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Проигрыватель',
    category: 'Musical instruments',
    image: './music/music-player.png',
    audioSrc: './audio/record-player.mp3',
    id: 12,
    categoryId: 2,
  },
  {
    word: 'Saxophone',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Саксофон',
    category: 'Musical instruments',
    image: './music/saxophone.png',
    audioSrc: './audio/saxophone.mp3',
    id: 13,
    categoryId: 2,
  },
  {
    word: 'Triangle',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Треугольник',
    category: 'Musical instruments',
    image: './music/triangle.png',
    audioSrc: './audio/triangle.mp3',
    id: 14,
    categoryId: 2,
  },
  {
    word: 'Violin',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Скрипка',
    category: 'Musical instruments',
    image: './music/violin.png',
    audioSrc: './audio/violin.mp3',
    id: 15,
    categoryId: 2,
  },
  {
    word: 'Airplane',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Самолет',
    category: 'Travel',
    image: './travel/airplane.png',
    audioSrc: './audio/airplane.mp3',
    id: 16,
    categoryId: 3,
  },
  {
    word: 'Airport',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Аэропорт',
    category: 'Travel',
    image: './travel/airport.png',
    audioSrc: './audio/airport.mp3',
    id: 17,
    categoryId: 3,
  },
  {
    word: 'Backpack',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Рюкзак',
    category: 'Travel',
    image: './travel/backpack.png',
    audioSrc: './audio/backpack.mp3',
    id: 18,
    categoryId: 3,
  },
  {
    word: 'Camera',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Камера',
    category: 'Travel',
    image: './travel/camera.png',
    audioSrc: './audio/camera.mp3',
    id: 19,
    categoryId: 3,
  },
  {
    word: 'Compass',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Компас',
    category: 'Travel',
    image: './travel/compass.png',
    audioSrc: './audio/compass.mp3',
    id: 20,
    categoryId: 3,
  },
  {
    word: 'Earth',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Земля',
    category: 'Travel',
    image: './travel/earth.png',
    audioSrc: './audio/earth.mp3',
    id: 21,
    categoryId: 3,
  },
  {
    word: 'Paris',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Париж',
    category: 'Travel',
    image: './travel/paris.png',
    audioSrc: './audio/paris.mp3',
    id: 22,
    categoryId: 3,
  },
  {
    word: 'Train',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Поезд',
    category: 'Travel',
    image: './travel/train.png',
    audioSrc: './audio/train.mp3',
    id: 23,
    categoryId: 3,
  },
  {
    word: 'Face mask',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Защитная маска',
    category: 'Medicine',
    image: './medicine/face-mask.png',
    audioSrc: './audio/face_mask.mp3',
    id: 24,
    categoryId: 4,
  },
  {
    word: 'First aid bag',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Аптечка',
    category: 'Medicine',
    image: './medicine/first-aid-bag.png',
    audioSrc: './audio/first-aid-bag.m4a',
    id: 25,
    categoryId: 4,
  },
  {
    word: 'Injection',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Шприц',
    category: 'Medicine',
    image: './medicine/injection.png',
    audioSrc: './audio/injection.mp3',
    id: 26,
    categoryId: 4,
  },
  {
    word: 'Pills',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Таблетки',
    category: 'Medicine',
    image: './medicine/pills.png',
    audioSrc: './audio/pills.mp3',
    id: 27,
    categoryId: 4,
  },
  {
    word: 'Scalpel',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Скальпель',
    category: 'Medicine',
    image: './medicine/scalpel.png',
    audioSrc: './audio/scalpel.mp3',
    id: 28,
    categoryId: 4,
  },
  {
    word: 'Thermometer',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Термометр',
    category: 'Medicine',
    image: './medicine/thermometer.png',
    audioSrc: './audio/thermometer.mp3',
    id: 29,
    categoryId: 4,
  },
  {
    word: 'Virus',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Вирус',
    category: 'Medicine',
    image: './medicine/virus.png',
    audioSrc: './audio/virus.mp3',
    id: 30,
    categoryId: 4,
  },
  {
    word: 'X-ray',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Рентген',
    category: 'Medicine',
    image: './medicine/x-ray.png',
    audioSrc: './audio/x-ray.mp3',
    id: 31,
    categoryId: 4,
  },
  {
    word: 'Fire extinguisher',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Огнетушитель',
    category: 'Factory',
    image: './factory/fire-extinguisher.png',
    audioSrc: './audio/extinguisher.mp3',
    id: 32,
    categoryId: 5,
  },
  {
    word: 'Forklift',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Погрузчик',
    category: 'Factory',
    image: './factory/forklift.png',
    audioSrc: './audio/forklift.mp3',
    id: 33,
    categoryId: 5,
  },
  {
    word: 'Waste',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Отходы',
    category: 'Factory',
    image: './factory/waste.png',
    audioSrc: './audio/waste.mp3',
    id: 34,
    categoryId: 5,
  },
  {
    word: 'Barrel',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Бочка нефти',
    category: 'Factory',
    image: './factory/oil-barrel.png',
    audioSrc: './audio/barrel.mp3',
    id: 35,
    categoryId: 5,
  },
  {
    word: 'Helmet',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Каска',
    category: 'Factory',
    image: './factory/helmet.png',
    audioSrc: './audio/helmet.mp3',
    id: 36,
    categoryId: 5,
  },
  {
    word: 'Laser',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Лазер',
    category: 'Factory',
    image: './factory/laser.png',
    audioSrc: './audio/laser.mp3',
    id: 37,
    categoryId: 5,
  },
  {
    word: 'Gloves',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Перчатки',
    category: 'Factory',
    image: './factory/gloves.png',
    audioSrc: './audio/gloves.mp3',
    id: 38,
    categoryId: 5,
  },
  {
    word: 'Factory',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Завод',
    category: 'Factory',
    image: './factory/factory.png',
    audioSrc: './audio/factory.mp3',
    id: 39,
    categoryId: 5,
  },
  {
    word: 'Twitter',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Твиттер',
    category: 'Socail networks',
    image: './social/twitter.png',
    audioSrc: './audio/twitter.mp3',
    id: 40,
    categoryId: 6,
  },
  {
    word: 'Twitch',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Твич',
    category: 'Socail networks',
    image: './social/twitch.png',
    audioSrc: './audio/twitch.mp3',
    id: 41,
    categoryId: 6,
  },
  {
    word: 'Telegram',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Телеграм',
    category: 'Socail networks',
    image: './social/telegram.png',
    audioSrc: './audio/telegram.mp3',
    id: 42,
    categoryId: 6,
  },
  {
    word: 'Snapchat',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Снэпчат',
    category: 'Socail networks',
    image: './social/snapchat.png',
    audioSrc: './audio/snapchat.mp3',
    id: 43,
    categoryId: 6,
  },
  {
    word: 'Instagram',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Инстаграм',
    category: 'Socail networks',
    image: './social/instagram.png',
    audioSrc: './audio/instagram.mp3',
    id: 44,
    categoryId: 6,
  },
  {
    word: 'Facebook',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Фэйсбук',
    category: 'Socail networks',
    image: './social/facebook.png',
    audioSrc: './audio/facebook.mp3',
    id: 45,
    categoryId: 6,
  },
  {
    word: 'Discord',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Дискорд',
    category: 'Socail networks',
    image: './social/discord.png',
    audioSrc: './audio/discord.mp3',
    id: 46,
    categoryId: 6,
  },
  {
    word: 'Google',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Гугл',
    category: 'Socail networks',
    image: './social/chrome.png',
    audioSrc: './audio/google.mp3',
    id: 47,
    categoryId: 6,
  },
  {
    word: 'Anatomy',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Анатомия',
    category: 'Education',
    image: './education/anatomy.png',
    audioSrc: './audio/anatomy.mp3',
    id: 48,
    categoryId: 7,
  },
  {
    word: 'Atom',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Атом',
    category: 'Education',
    image: './education/atom.png',
    audioSrc: './audio/atom.mp3',
    id: 49,
    categoryId: 7,
  },
  {
    word: 'Blackboard',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Школьная доска',
    category: 'Education',
    image: './education/blackboard.png',
    audioSrc: './audio/blackboard.mp3',
    id: 50,
    categoryId: 7,
  },
  {
    word: 'Brain',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Мозг',
    category: 'Education',
    image: './education/brain.png',
    audioSrc: './audio/brain.mp3',
    id: 51,
    categoryId: 7,
  },
  {
    word: 'Chemistry',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Химия',
    category: 'Education',
    image: './education/chemistry.png',
    audioSrc: './audio/chemistry.mp3',
    id: 52,
    categoryId: 7,
  },
  {
    word: 'Geography',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'География',
    category: 'Education',
    image: './education/geography.png',
    audioSrc: './audio/geography.mp3',
    id: 53,
    categoryId: 7,
  },
  {
    word: 'Painters palette',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Палитра',
    category: 'Education',
    image: './education/paint-palette.png',
    audioSrc: "./audio/painter's-palette.mp3",
    id: 54,
    categoryId: 7,
  },
  {
    word: 'Telescope',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Телескоп',
    category: 'Education',
    image: './education/telescope.png',
    audioSrc: './audio/telescope.mp3',
    id: 55,
    categoryId: 7,
  },
  {
    word: 'Ball',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Мяч',
    category: 'Relaxation',
    image: './chill/ball.png',
    audioSrc: './audio/ball.mp3',
    id: 56,
    categoryId: 8,
  },
  {
    word: 'Chair',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Лежак',
    category: 'Relaxation',
    image: './chill/chair.png',
    audioSrc: './audio/chair.mp3',
    id: 57,
    categoryId: 8,
  },
  {
    word: 'Cocktail',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Коктейль',
    category: 'Relaxation',
    image: './chill/cocktail.png',
    audioSrc: './audio/cocktail.mp3',
    id: 58,
    categoryId: 8,
  },
  {
    word: 'Hut',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Хижина',
    category: 'Relaxation',
    image: './chill/hut.png',
    audioSrc: './audio/hut.mp3',
    id: 59,
    categoryId: 8,
  },
  {
    word: 'Palm tree',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Пальма',
    category: 'Relaxation',
    image: './chill/palm-tree.png',
    audioSrc: './audio/palm_tree.mp3',
    id: 60,
    categoryId: 8,
  },
  {
    word: 'Pool',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Бассейн',
    category: 'Relaxation',
    image: './chill/Pool.png',
    audioSrc: './audio/pool.mp3',
    id: 61,
    categoryId: 8,
  },
  {
    word: 'Sandals',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Шлепки',
    category: 'Relaxation',
    image: './chill/sandals.png',
    audioSrc: './audio/sandals.mp3',
    id: 62,
    categoryId: 8,
  },
  {
    word: 'Diver mask',
    clicks: 0,
    correct: 0,
    wrong: 0,
    error: 0,
    translation: 'Маска дайвера',
    category: 'Relaxation',
    image: './chill/snorkel.png',
    audioSrc: './audio/diver-mask.m4a',
    id: 63,
    categoryId: 8,
  },
]
